### ISSUE TITLE
Rendering slides runs forever

### ISSUE THREAD

**Issue by bka-hm** [wallento/bbb-scrape#7]
I am trying to back up BBB sessions with PDF presentations+audio+annotations (rarely +webcam) around 90 mins, ~100 slides. 

Installed version is bbb-scrape-0.4.

`bbb-scrape https://bbb.cs.hm.edu/playback/presentation/2.0/playback.html?meetingId=[ID]`

prints 
    ++ Scrape from server
    ++ Stored webcams to webcams.mp4
    ++ Generate frames
    ++ Render slides.mp4
and keeps running. Had to terminate it manually after >10h. 

Output folder contains slides as PNGs, webcams.mp4 (correct length, contains audio), slides.mp4 (lenght ~3 hours, padded after 90mins with the last slide).

Expected: Process terminates, slides are rendered to the length of the meeting.

**Comment by wallento** [comment]
@mgudemann you had a fix for this, right?

**Comment by wallento** [comment]
IIRC the issue is about sorting of the timestamps and an absurdly lengthy delay in the mux file

**Comment by wallento** [comment]
Can you verify its solved in 1.0?

**Comment by bka-hm** [comment]
Yep, output is a slides.mp4 and a webcam.mp4, both of correct length.
