### ISSUE TITLE
Cannot handle multiple presentations.

### ISSUE THREAD

**Issue by bka-hm** [wallento/bbb-scrape#9]
In meetings with multiple presentations (PDFs), slides with the same slide number are all taken from the same presentation.

Installed version is bbb-scrape-1.0.

Minimal example (kinda) is: 
Record a meeting showing slides of presentation A, slides 1, 2, then presentation B, slides, 1, 2, 3
Output shows A, slides 1, 2, then A, slides 1, 2 (again), then B, slide 3.

Expected: Output shows slides as A 1, 2, B 1, 2, 3

**Comment by wallento** [comment]
Can you please check 1.0.1

**Comment by bka-hm** [comment]
works like charm.
